### ISSUE TITLE
Deleting handled sizes deletes SVG files

### ISSUE THREAD

**Issue by loilo** [tekod/fws-resize-on-demand#1]
First and foremost: Thanks for making this plugin! It's massively useful when working with a lot of image sizes. 👍 

Unfortunately though, the plugin's "delete" feature conflicts with using the [SVG Support](https://de.wordpress.org/plugins/svg-support/) plugin.
That plugin allows uploading `.svg` files to WordPress, faking the image sizes array via a hook (with all of them pointing back to the original SVG file).

However, because all sizes point to the original SVG file, all SVG files uploaded fall victim to removal when using your plugin's "delete" feature.

This would be an easy fix and I'd be happy to contribute a pull request here (already solved the issue locally), but I'm under the impression that the GitHub repo is not up to date – at least the plugin code itself looks newer than the code here on GitHub.

What do you think? :)

**Comment by fws-miroslav** [comment]
Thank you for kind words.
I am not sure what exactly you want to achive but if you have soloution for your use case create pull request, 
repo is updated (thank you on pointing on that).
